# Generated by Django 5.0.1 on 2024-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('intensity', models.FloatField()),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=50)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('impact', models.TextField(blank=True)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=50)),
                ('relevance', models.FloatField()),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('likelihood', models.FloatField()),
            ],
        ),
    ]
