# Generated by Django 5.0.1 on 2024-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_data',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
