# Generated by Django 5.0.1 on 2024-03-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0002_alter_dashboard_data_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_data',
            name='intensity',
            field=models.FloatField(null=True),
        ),
    ]
