# Generated by Django 5.0.1 on 2024-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_dashboard_data_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_data',
            name='likelihood',
            field=models.FloatField(null=True),
        ),
    ]
