# Generated by Django 5.0.1 on 2024-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_alter_dashboard_data_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard_data',
            name='relevance',
            field=models.FloatField(null=True),
        ),
    ]
